apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-pvc
  namespace: linkding
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
