apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.2
    path: /volume1/quub
  persistentVolumeReclaimPolicy: Retain

